import { S3Client, HeadObjectCommand } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";

export const uploadToFilebase = async (file, onProgress) => {
  const accessKeyId = import.meta.env.VITE_FILEBASE_ACCESS_KEY;
  const secretAccessKey = import.meta.env.VITE_FILEBASE_SECRET_KEY;
  const bucketName = import.meta.env.VITE_FILEBASE_BUCKET;

  if (!accessKeyId || !secretAccessKey || !bucketName) {
    throw new Error("Filebase credentials or bucket name are missing in your Vercel/local Environment Variables.");
  }

  const s3 = new S3Client({
    endpoint: "https://s3.filebase.com",
    region: "us-east-1",
    credentials: {
      accessKeyId,
      secretAccessKey,
    },
  });

  // Ensure unique key to prevent overwrites in the bucket
  const key = `${Date.now()}_${file.name}`;

  const upload = new Upload({
    client: s3,
    params: {
      Bucket: bucketName,
      Key: key,
      Body: file,
      ContentType: file.type || "application/octet-stream",
    },
  });

  upload.on("httpUploadProgress", (progress) => {
    if (onProgress) {
      onProgress(progress);
    }
  });

  // Wait for upload to complete
  await upload.done();

  // Fetch object metadata to retrieve the IPFS CID generated by Filebase
  const headCommand = new HeadObjectCommand({
    Bucket: bucketName,
    Key: key,
  });

  const headResponse = await s3.send(headCommand);
  const cid = headResponse.Metadata && headResponse.Metadata.cid;

  if (!cid) {
    throw new Error("Failed to retrieve IPFS CID from Filebase servers.");
  }

  return `ipfs://${cid}`;
};
